apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: nada
  name: nada-metabase
  namespace: nada
spec:
  env:
  - name: MB_JETTY_HOST
    value: 0.0.0.0
  - name: MB_JETTY_PORT
    value: "3000"
  - name: MB_DB_TYPE
    value: postgres
  - name: MB_PASSWORD_COMPLEXITY
    value: normal
  - name: MB_PASSWORD_LENGTH
    value: "6"
  - name: JAVA_TIMEZONE
    value: UTC
  - name: MB_EMOJI_IN_LOGS
    value: "true"
  envFrom:
  - secret: nada-metabase
  gcp:
    sqlInstances:
    - databases:
      - name: metabase
      type: POSTGRES_12
  image: ghcr.io/navikt/metabase:latest
  ingresses:
  - https://metabase.dev.intern.nav.no
  port: 3000
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
