apiVersion: v1
data:
  MB_DB_DBNAME: {{ db_name_dev }}
  MB_DB_HOST: {{ db_host_dev }}
  MB_DB_PASS: {{ db_pass_dev }}
  MB_DB_PORT: {{ db_port_dev }}
  MB_DB_URL: {{ db_url_dev }}
  MB_DB_USER: {{ db_user_dev }}
kind: Secret
metadata:
  labels:
    app: metabase
    team: nada
  name: google-sql-nada-metabase
  namespace: nada
type: Opaque
---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: nada
  name: metabase
  namespace: nada
spec:
  env:
  - name: MB_DB_TYPE
    value: postgres
  - name: JAVA_TIMEZONE
    value: UTC
  - name: MB_EMOJI_IN_LOGS
    value: "true"
  - name: MB_GOOGLE_AUTH_AUTO_CREATE_ACCOUNTS_DOMAIN
    value: nav.no
  - name: MB_GOOGLE_AUTH_CLIENT_ID
    value: 270239535136-gs7ot9ba0c0rvfdlmos6tt63mlv0ksc7.apps.googleusercontent.com
  - name: MB_PLUGINS_DIR
    value: "/tmp"
  envFrom:
  - secret: metabase
  gcp:
    sqlInstances:
    - databases:
      - name: metabase
      type: POSTGRES_12
  image: metabase/metabase:v0.42.3
  ingresses:
  - https://metabase.intern.nav.no
  port: 3000
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: "1"
      memory: 1024Mi
