apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: nada
  name: metabase
  namespace: nada
  annotations:
    {{#each annotations}}
    {{this.key}}: "{{this.value}}"
    {{/each}}
spec:
  env:
  - name: MB_SITE_URL
    value: https://metabase.intern.nav.no
  - name: MB_DB_USER
    value: metabase
  {{#each envs}}
  - name: {{this.name}}
    value: "{{this.value}}"
  {{/each}}
  envFrom:
  - secret: metabase
  gcp:
    sqlInstances:
    - databases:
      - name: metabase
      type: POSTGRES_12
      flags:
        - name: max_connections
          value: "100"
      tier: db-g1-small
  image: {{image}}
  ingresses:
  - https://metabase.intern.nav.no
  - https://metabase-inside.intern.nav.no
  liveness:
    path: /api/health
  startup:
    initialDelay: 40
    periodSeconds: 10
    failureThreshold: 20
    path: /api/health
  readiness:
    path: /api/health
  port: 3000
  replicas:
    max: 4
    min: 2
  resources:
    limits:
      cpu: 500m
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 1024Mi
  accessPolicy:
    inbound:
      rules:
        - application: nada-backend
    outbound:
      external:
      {{#externalhosts}}
      - host: "{{ . }}"
      {{/externalhosts}}
      - host: smtp.adeo.no
        ports:
        - port: 26

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: metabase-alert
  namespace: nada
  labels:
    team: nada
spec:
  groups:
  - name: metabase-alert
    rules:
    - alert: InstanceDown
      expr: kube_deployment_status_replicas_available{namespace="nada", deployment="metabase"} == 0
      for: 2m
      annotations:
        consequence: Metabase is unavailable
        action: "`kubectl describe pod <podname>` -> `kubectl logs <podname>`"
        summary: |-
          No metabase pods are running in prod-gcp
      labels:
        namespace: nada
        severity: critical
